site_name: 'NadekoBot'
site_url: 'https://nadeko.bot'
repo_url: 'https://gitlab.com/kwoth/nadekobot'
site_author: 'Kwoth'
nav:
- Home: 'index.md'
- Features:
    - 'Permissions System': 'perms.md'
    - Expressions: 'expressions.md'
    - Placeholders: 'placeholders.md'
    - Configs: 'configs.md'
- Guides:    
    - 'Guide': 'guides/guides.md'
- 'Commands List': 'https://nadeko.bot/commands/v3'
- 'Frequently Asked Questions': 'faq.md'
- '❤ Contribute ❤': 'contribute.md'
- License: 'license.md'
theme: 'material'
