site_name: NadekoBot
pages:
- Home: index.md
- Guides:
    - Guide: guides/guides.md
- Commands:
    - Commands List: https://nadeko.bot/commands/v3
- Features Explained:
    - Permissions System: perms.md
    - Expressions: expressions.md
    - Placeholders: placeholders.md
    - Configs: configs.md
- Frequently Asked Questions: faq.md
- ❤ Contribute ❤: contribute.md
- License: license.md

theme: readthedocs
