version: '3'
services:
  # database
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
  searchimages-service:
    stdin_open: true
    tty: true
    build: 
      context: SearchImages/
    ports:
      - "25158:2452"
    volumes:
      - "./SearchImages:/app/"
    depends_on:
      - db