author:
  name: Kwoth#2452
  id: 105635576866156544
entries:
- title: Blue Stahli - "Corner"
  q: https://youtube.com/watch?v=r1UexAuAODI
  type: YouTube
- title: Blue Stahli - Shotgun Senorita
  q: https://youtube.com/watch?v=Xku0zPWZn8o
  type: YouTube
- title: Blue Stahli - ULTRAnumb (Official Music Video)
  q: https://youtube.com/watch?v=mAxOulZm_Zg
  type: YouTube
- title: Blue Stahli - "Takedown"
  q: https://youtube.com/watch?v=hZbuigSlrdU
  type: YouTube
- title: Blue Stahli - "Anti You"
  q: https://youtube.com/watch?v=-jMj8O0k6xg
  type: YouTube
- title: Blue Stahli - Lakes Of Flame
  q: https://youtube.com/watch?v=ZYTWqJLBGo8
  type: YouTube
- title: Blue Stahli - Rockstar
  q: https://youtube.com/watch?v=t7OKs-zqxXA
  type: YouTube
- title: Blue Stahli - I Am The Beast
  q: https://youtube.com/watch?v=yGAwCFunIjA
  type: YouTube
- title: Blue Stahli - Ready Aim Fire (Official Lyric Video)
  q: https://youtube.com/watch?v=5raCE5o3m1M
  type: YouTube
- title: Blue Stahli - "Scrape"
  q: https://youtube.com/watch?v=W7tT2WDzNTU
  type: YouTube
- title: Blue Stahli - "Throw Away"
  q: https://youtube.com/watch?v=Wgsu5iF6cAk
  type: YouTube
- title: Blue Stahli - Enemy (Official Lyric Video)
  q: https://youtube.com/watch?v=W-NfGeHbvjA
  type: YouTube
- title: Blue Stahli - Down In Flames (Official Lyric Video)
  q: https://youtube.com/watch?v=jATOZhxX1CY
  type: YouTube
- title: Blue Stahli - "Metamorphosis"
  q: https://youtube.com/watch?v=WtGA-xcL958
  type: YouTube
- title: Blue Stahli - Armageddon (Official Lyric Video)
  q: https://youtube.com/watch?v=85dUlxEnE8o
  type: YouTube
- title: Blue Stahli - The Fall (Official Lyric Video)
  q: https://youtube.com/watch?v=WeeivC7ZtHk
  type: YouTube
- title: Blue Stahli - The Pure and The Tainted
  q: https://youtube.com/watch?v=afY-Od_hDRo
  type: YouTube
- title: Blue Stahli - "Doubt"
  q: https://youtube.com/watch?v=5m3Pc77egSg
  type: YouTube
- title: Sunset Neon - Tonight (Official Lyric Video)
  q: https://youtube.com/watch?v=IUvvGf8T7wM
  type: YouTube
- title: Blue Stahli - "Kill Me Every Time"
  q: https://youtube.com/watch?v=LKLNsvGjfn4
  type: YouTube
- title: Blue Stahli - Shoot Em Up
  q: https://youtube.com/watch?v=bztxC9EFfCk
  type: YouTube
- title: Blue Stahli - Suit Up (feat. Southpaw Swagger)
  q: https://youtube.com/watch?v=tRlOSjCymkM
  type: YouTube
- title: Blue Stahli - Superhero Showdown
  q: https://youtube.com/watch?v=xuM765lgybM
  type: YouTube
- title: Blue Stahli - Burning Bridges (Lyric Video)
  q: https://youtube.com/watch?v=865iVQG0X00
  type: YouTube
- title: Dead Rising 2 Randy's Boss Soundtrack
  q: https://youtube.com/watch?v=jm9FjldIZxA
  type: YouTube
- title: Blue Stahli - Overklock
  q: https://youtube.com/watch?v=1SHi01NLh7g
  type: YouTube
- title: Blue Stahli - "Give Me Everything You've Got"
  q: https://youtube.com/watch?v=VDtlIQ_hhi8
  type: YouTube
- title: Sunset Neon - Got You (Official Lyric Video)
  q: https://youtube.com/watch?v=YlsKhAZqQf0
  type: YouTube
- title: Blue Stahli - Demon
  q: https://youtube.com/watch?v=ZmRza63gPaE
  type: YouTube
- title: Blue Stahli - You'll Get What's Coming (feat.  Mark Salomon)
  q: https://youtube.com/watch?v=cCmhfc_obsw
  type: YouTube
- title: Sunset Neon - Lazer Pink
  q: https://youtube.com/watch?v=Cc_J3uzDgZ4
  type: YouTube
- title: Blue Stahli - Headshot
  q: https://youtube.com/watch?v=XpPB9FVS_lk
  type: YouTube
- title: Blue Stahli - Reload
  q: https://youtube.com/watch?v=mGmBuDDSeHU
  type: YouTube
- title: Blue Stahli - The Devil (ANX Remix)
  q: https://youtube.com/watch?v=bcBVvWCzMs8
  type: YouTube
- title: Blue Stahli - Not Over Til We Say So (feat. Emma Anzai) [Rabbit Junk Remix]
  q: https://youtube.com/watch?v=nxXf3kSfZxM
  type: YouTube
- title: Blue Stahli - Accelerant
  q: https://youtube.com/watch?v=m7b9qemx-og
  type: YouTube
- title: Sunset Neon - Never Dance Again (Battle Tapes Remix)
  q: https://youtube.com/watch?v=cmW4d7CrqBw
  type: YouTube
- title: Blue Stahli - The Sound Of War
  q: https://youtube.com/watch?v=zqS0CnxvsrU
  type: YouTube
- title: Blue Stahli-Mystique
  q: https://youtube.com/watch?v=MfUQJFbux_A
  type: YouTube
- title: Blue Stahli - Car Chase Club Action
  q: https://youtube.com/watch?v=JFOtJC-_Tk8
  type: YouTube
- title: Blue Stahli - Let's Go
  q: https://youtube.com/watch?v=lREZy9LBsKI
  type: YouTube
- title: Blue Stahli - Rebel Yell (Cinematic Version)
  q: https://youtube.com/watch?v=Ud8FQ9JToLI
  type: YouTube
- title: Blue Stahli - Bulletproof
  q: https://youtube.com/watch?v=RhGnjcumn4M
  type: YouTube
- title: Blue Stahli - Nemesis
  q: https://youtube.com/watch?v=2a17z3YH2DU
  type: YouTube
- title: 'Nightcore - The Beginning '
  q: https://youtube.com/watch?v=0ZBkqJoEXKs
  type: YouTube
- title: Blue Stahli - Futureproof
  q: https://youtube.com/watch?v=syyqfa7ZUcM
  type: YouTube
- title: Blue Stahli- Leadfoot Getaway [Extended Version]
  q: https://youtube.com/watch?v=px-ti-FnAYE
  type: YouTube
- title: Sunset Neon - Starlight
  q: https://youtube.com/watch?v=eiIQ-j8olns
  type: YouTube
- title: Blue Stahli   Retribution
  q: https://youtube.com/watch?v=IfO26vLqGr0
  type: YouTube
- title: Blue Stahli - Railgun
  q: https://youtube.com/watch?v=9CDXfAoYcKM
  type: YouTube
- title: Blue Stahli - Rapid Fire
  q: https://youtube.com/watch?v=MvMlIxhRLrQ
  type: YouTube
- title: Blue Stahli - Lightspeed Combat
  q: https://youtube.com/watch?v=Y-Pqs2sCwVI
  type: YouTube
- title: Blue Stahli - Doublequick
  q: https://youtube.com/watch?v=k3sfSplgrAY
  type: YouTube
- title: Blue Stahli - Red Carpet Rush
  q: https://youtube.com/watch?v=5z7DI4IQ0vE
  type: YouTube
- title: '[UNAVAILABLE] Used 1995 Carver 390 Cockpit Motor Yacht in Lake Texoma, Texas'
  q: https://youtube.com/watch?v=RkLwag6lJdY
  type: YouTube
- title: Blue Stahli - Outlaw
  q: https://youtube.com/watch?v=XcsSGbkCO7g
  type: YouTube
- title: Blue Stahli - The Destroyer Of All Things
  q: https://youtube.com/watch?v=Fw8CaDXo1jw
  type: YouTube
- title: East
  q: https://youtube.com/watch?v=hRI5-wZxnPM
  type: YouTube
- title: Blue Stahli - Awaken
  q: https://youtube.com/watch?v=xMdOgCdHxjY
  type: YouTube
- title: Sunset Neon - You Are The Sun (Official Lyric Video)
  q: https://youtube.com/watch?v=hFW_2Vo1kIM
  type: YouTube
- title: Blue Stahli - Hell Arrives
  q: https://youtube.com/watch?v=DVRMGxPHmw8
  type: YouTube
- title: Blue Stahli - Glitterati
  q: https://youtube.com/watch?v=rc3VuJ0wVfk
  type: YouTube
- title: Blue Stahli - Atom Smasher
  q: https://youtube.com/watch?v=KmlzGDRygLM
  type: YouTube
- title: Blue Stahli - So So Bad
  q: https://youtube.com/watch?v=2WU2_xT_pTM
  type: YouTube
- title: Hit Me
  q: https://youtube.com/watch?v=L9adIsRR5zI
  type: YouTube
- title: Blue Stahli - 88 Rounds Per Minute
  q: https://youtube.com/watch?v=hRNsV-klDVw
  type: YouTube
- title: Blue Stahli - Go
  q: https://youtube.com/watch?v=Gv3-qER1pBc
  type: YouTube
- title: The Ultimate
  q: https://youtube.com/watch?v=-jVkTxN_8Dw
  type: YouTube
- title: Premeditated - Blue Stahli
  q: https://youtube.com/watch?v=JOP9oARu-2c
  type: YouTube
- title: Blue Stahli-The Perfect Heist
  q: https://youtube.com/watch?v=Pu_vv5hVGGk
  type: YouTube
- title: Blue Stahli - Jackhammer Manifesto
  q: https://youtube.com/watch?v=zaz-YZ-akWk
  type: YouTube
- title: Disco Punks on Jolt - Blue Stahli
  q: https://youtube.com/watch?v=BXLf1CAdDgM
  type: YouTube
- title: Blue Stahli - Secret Agent Business
  q: https://youtube.com/watch?v=Aln8U4SJ_cg
  type: YouTube
- title: Blue Stahli - Ready For Battle
  q: https://youtube.com/watch?v=cjRk-_R4HuY
  type: YouTube
- title: Blue Stahli - This Will Make You Love Again  (IAMX Cover)
  q: https://youtube.com/watch?v=W1eJlY6ljC4
  type: YouTube
- title: Blue Stahli - Regret
  q: https://youtube.com/watch?v=OiFu0b4Na7Y
  type: YouTube
- title: How to fix Printer Error 0xF1 Epson L565
  q: https://youtube.com/watch?v=L2UHrDlEgwc
  type: YouTube
- title: Blue Stahli - Jet Set
  q: https://youtube.com/watch?v=hbbBKTzhmfE
  type: YouTube
- title: Blue Stahli - Fashionista
  q: https://youtube.com/watch?v=E67NHaWBFkI
  type: YouTube
- title: Rumbleshaker
  q: https://youtube.com/watch?v=NjEJuFomMQU
  type: YouTube
- title: Blue Stahli - Blast Action
  q: https://youtube.com/watch?v=RcP2Uejed5o
  type: YouTube
- title: Blue Stahli - Smackdown
  q: https://youtube.com/watch?v=gAxL5M9LNFI
  type: YouTube
- title: Blue Stahli - Chaser
  q: https://youtube.com/watch?v=CO9HECNNrrE
  type: YouTube
- title: Metrocenter 84
  q: https://youtube.com/watch?v=T_L_9yistJM
  type: YouTube
- title: Blue Stahli - Celebrity Mashup
  q: https://youtube.com/watch?v=LmdQmphSxe0
  type: YouTube
- title: Blue Stahli - High Heeled Low Life
  q: https://youtube.com/watch?v=iJsXqM0bwDY
  type: YouTube
- title: Not Over Til We Say So (feat. Emma Anzai) (Rabbit Junk Remix)
  q: https://youtube.com/watch?v=_wh_8gj2Y1E
  type: YouTube
- title: Blue Stahli - The Destroyer Of All Things (Antisleep Vol.3)
  q: https://youtube.com/watch?v=1ko4HUHQlZg
  type: YouTube
- title: Blue Stahli - Three Piece Suit
  q: https://youtube.com/watch?v=Z6O2f8AWiL8
  type: YouTube
- title: Cyberpunk Dominion
  q: https://youtube.com/watch?v=XJTvDgrsPMs
  type: YouTube
- title: Sunset Neon - After Hours
  q: https://youtube.com/watch?v=p0WnNLkUj7c
  type: YouTube
- title: Blue Stahli - Trash Glamour Rock Chick
  q: https://youtube.com/watch?v=BkOSwWMzXAo
  type: YouTube
- title: Blue Stahli - Dirty Down
  q: https://youtube.com/watch?v=mBC_d80y8hI
  type: YouTube
- title: Blue Stahli - Tenacity
  q: https://youtube.com/watch?v=z1aqcirlFHk
  type: YouTube
- title: Blue Stahli - Death Hammer
  q: https://youtube.com/watch?v=vTU2YpM7UZ4
  type: YouTube
- title: Sunset Neon - Kiss (Prince Cover)
  q: https://youtube.com/watch?v=3JTbiXFwKJI
  type: YouTube
- title: Blue Stahli-High Roller Mojo
  q: https://youtube.com/watch?v=ov98nl1mfCQ
  type: YouTube
- title: Blue Stahli - Vegas, Baby
  q: https://youtube.com/watch?v=WczgTFTvkKw
  type: YouTube
- title: Blue Stahli - Kiss Kiss Bang Bang
  q: https://youtube.com/watch?v=RZsvbY1x578
  type: YouTube
- title: Blue Stahli - Battleground
  q: https://youtube.com/watch?v=gxYO8J0JnmU
  type: YouTube
- title: Blue Stahli - Sunset Neon 1hr
  q: https://youtube.com/watch?v=dkyQIYAO__c
  type: YouTube
- title: Blue Stahli - Ghost of Love (David Lynch Cover)
  q: https://youtube.com/watch?v=1dDnCPvBc70
  type: YouTube
- title: Blue Stahli - Slick
  q: https://youtube.com/watch?v=DhViY-czqB8
  type: YouTube
- title: Blue Stahli - Dragstrip Burnout
  q: https://youtube.com/watch?v=U8jpx6AM7IU
  type: YouTube
- title: Blue Stahli - Fierce Pop Starlet
  q: https://youtube.com/watch?v=ARIQGOmY6oo
  type: YouTube
- title: Sunset Neon - Opening Title Sequence
  q: https://youtube.com/watch?v=QL9O-h2Xk1M
  type: YouTube
- title: Blue Stahli - The Ritual
  q: https://youtube.com/watch?v=T9Gx6iHK04I
  type: YouTube
- title: Stangblack
  q: https://youtube.com/watch?v=8y8v7VxY2Rg
  type: YouTube
- title: Blue Stahli - Rebellion Anthem
  q: https://youtube.com/watch?v=QdLMMju6aQk
  type: YouTube
- title: Blue Stahli - Reverse Tension
  q: https://youtube.com/watch?v=ntrt-Fd3HdQ
  type: YouTube
- title: Blue Stahli - Blue Stahli
  q: https://youtube.com/watch?v=9vBe5BST7AA
  type: YouTube
- title: You'll Get What's Coming (feat. Mark Salomon) (Sebastian Komor Remix)
  q: https://youtube.com/watch?v=oIuKsEg3ixc
  type: YouTube
- title: Strut
  q: https://youtube.com/watch?v=1dlgHAVzNUM
  type: YouTube
- title: Not Over Til We Say So (Formal One Remix)
  q: https://youtube.com/watch?v=PweBsAGM-Cw
  type: YouTube
- title: Something in the Woods
  q: https://youtube.com/watch?v=Of2ELaUVEDs
  type: YouTube
- title: Run The Track (Instrumental)
  q: https://youtube.com/watch?v=3iAZ925Ngnw
  type: YouTube
- title: Remorse Code & Blue Stahli - Bandito
  q: https://youtube.com/watch?v=e94jPzHlJy8
  type: YouTube
- title: Blue Stahli/Emma Anzai - Not Over Til We Say So (guitar cover)
  q: https://youtube.com/watch?v=p0Q1hguV0io
  type: YouTube
- title: Not Over Til We Say So (Instrumental)
  q: https://youtube.com/watch?v=aOmW2K54RoA
  type: YouTube
- title: Blue Stahli - Glitterati
  q: https://youtube.com/watch?v=zzxNnAs0GXY
  type: YouTube
