author:
  name: ˞˞#8008
  id: 222751757304856576
entries:
- title: Eminem - Never Love Again (Lyrics)
  q: https://youtube.com/watch?v=9JWdQCPRUvg
  type: YouTube
- title: Eminem - Farewell (Lyrics)
  q: https://youtube.com/watch?v=OoGt-tyDIfA
  type: YouTube
- title: You Gon' Learn (feat. Royce Da 5'9" & White Gold) [Official Audio]
  q: https://youtube.com/watch?v=RnNJ7uVR7hM
  type: YouTube
- title: Leaving Heaven (feat. Skylar Grey) [Official Audio]
  q: https://youtube.com/watch?v=ftujE679Wx0
  type: YouTube
- title: Eminem - In Too Deep [Lyrics]
  q: https://youtube.com/watch?v=miXocUmJQuA
  type: YouTube
- title: Lock It Up (feat. Anderson .Paak) [Official Audio]
  q: https://youtube.com/watch?v=7jR65jnUyvA
  type: YouTube
- title: Godzilla (feat. Juice WRLD) [Official Audio]
  q: https://youtube.com/watch?v=9XvXF1LrWgA
  type: YouTube
- title: Eminem - Fack [HQ Lyrics]
  q: https://youtube.com/watch?v=jgr1I7CdMeY
  type: YouTube
- title: Eminem - Asshole ft. Skylar Grey (Audio)
  q: https://youtube.com/watch?v=4LG-LOLIaSs
  type: YouTube
- title: Eminem - Untitled (Lyrics) [HD & HQ]
  q: https://youtube.com/watch?v=wStyrkBM5Z4
  type: YouTube
- title: Eminem - W.T.P. Lyrics [HD]
  q: https://youtube.com/watch?v=KZPAIn-yVTg
  type: YouTube
- title: Eminem Ft Kendrick Lamar -  Love Game (Marshall Mathers LP 2 -  Lyrics HD)
  q: https://youtube.com/watch?v=tdZHuPsomd4
  type: YouTube
- title: Eminem - Beautiful (Edited) (Explicit)
  q: https://youtube.com/watch?v=avLxcVkPgug
  type: YouTube
- title: Eminem, Royce da 5'9", Big Sean, Danny Brown, Dej Loaf, Trick Trick - Detroit Vs. Everybody
  q: https://youtube.com/watch?v=hCdgDxQbW_U
  type: YouTube
- title: roman revenge - Eminem's verses only
  q: https://youtube.com/watch?v=h1yDJyzTvOs
  type: YouTube
- title: Nicki Minaj ft. Eminem & Labrinth - Majesty [Lyrics] (Eminem Verse Only)
  q: https://youtube.com/watch?v=8lM3zy3dcO4
  type: YouTube
- title: Drake, Kanye West, Lil Wayne, Eminem - Forever (Explicit Version)
  q: https://youtube.com/watch?v=eDuRoPIOBjE
  type: YouTube
- title: Logic - Homicide (feat. Eminem) (Official Audio)
  q: https://youtube.com/watch?v=mfqsEpjEtrw
  type: YouTube
- title: Eminem - Berzerk (Official Music Video) (Explicit)
  q: https://youtube.com/watch?v=ab9176Srb5Y
  type: YouTube
- title: Eminem ft. Rihanna - The Monster (Explicit) [Official Video]
  q: https://youtube.com/watch?v=EHkozMIXZ8w
  type: YouTube
- title: Eminem - Not Alike (ft. Royce Da 5'9") (Lyrics)
  q: https://youtube.com/watch?v=91bcI3TcAtM
  type: YouTube
- title: Eminem - Lucky You ft. Joyner Lucas
  q: https://youtube.com/watch?v=mvSItvjFE1c
  type: YouTube
- title: Eminem - The Real Slim Shady (Official Video - Clean Version)
  q: https://youtube.com/watch?v=eJO5HU_7_1w
  type: YouTube
- title: Eminem - We Made You (Official Video)
  q: https://youtube.com/watch?v=RSdKmX2BH7o
  type: YouTube
- title: Is ‘Higher Learning’ Ice Cube’s Acting Apex Mountain? | The Rewatchables | The Ringer
  q: https://youtube.com/watch?v=QwhUKr0-bOU
  type: YouTube
- title: Eminem - Speedom spits 480 words in 83 seconds
  q: https://youtube.com/watch?v=Vbfop_Lfnhw
  type: YouTube
- title: Eminem - The Ringer (Lyrics)
  q: https://youtube.com/watch?v=tT150Zl0Ay0
  type: YouTube
- title: Eminem - All She Wrote Solo Version Lyrics 720p
  q: https://youtube.com/watch?v=rvdq3rjFZRE
  type: YouTube
- title: Eminem - Offended (Lyrics)
  q: https://youtube.com/watch?v=kws6l3DH-G4
  type: YouTube
- title: B.o.B - Airplanes Part. 2 (Ft. Eminem, Hayley Williams) [CDQ] W/Lyrics
  q: https://youtube.com/watch?v=aJ_M4pV_eOQ
  type: YouTube
