author:
  name: Kwoth#2452
  id: 105635576866156544
entries:
- title: Rise of Nations soundtrack - DarkForest
  q: https://youtube.com/watch?v=cjOpfRY_dZU
  type: YouTube
- title: Rise of Nations soundtrack - HighStrung
  q: https://youtube.com/watch?v=oeYH-2_93qY
  type: YouTube
- title: Rise of Nations soundtrack - Morocco
  q: https://youtube.com/watch?v=MFglEGnOK5k
  type: YouTube
- title: Rise of Nations soundtrack - Gobi
  q: https://youtube.com/watch?v=1JdcFdFeJTs
  type: YouTube
- title: Rise of Nations soundtrack - SriLanka
  q: https://youtube.com/watch?v=CLFfnmObLgc
  type: YouTube
- title: Rise of Nations soundtrack - Santiago
  q: https://youtube.com/watch?v=R0wkc5_KJ74
  type: YouTube
- title: Rise of Nations soundtrack - SimpleSong
  q: https://youtube.com/watch?v=2iJtoYKTEG8
  type: YouTube
