eightBallResponses:
- Most definitely yes.
- For sure.
- Totally!
- Of course!
- As I see it, yes.
- My sources say yes.
- Yes.
- Most likely.
- Perhaps...
- Maybe...
- Hm, not sure.
- It is uncertain.
- Ask me again later.
- Don't count on it.
- Probably not.
- Very doubtful.
- Most likely no.
- Nope.
- No.
- My sources say no.
- Don't even think about it.
- Definitely no.
- NO - It may cause disease contraction!
